### ISSUE TITLE
daily_sign.py执行总是出错

### ISSUE THREAD

**Issue by barreler126** [tech-shrimp/GithubActionSample#11]
Traceback (most recent call last):
  File "D:\me\GithubActionSample\daily_sign.py", line 30, in <module>
    response = requests.post(url=url, headers=headers, timeout=30)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

进程已结束，退出代码为 1

**Comment by xiaonan-37021** [comment]
我的也有这个问题

**Comment by xiaonan-37021** [comment]
> 
把cookie哪里改成cookie = os.environ.get("JD_COOKIE", "").strip()就行

**Comment by xiaonan-37021** [comment]
没问题的话，关闭一下吧
